---
hosts:
  - 50.16.88.200
  - 54.147.243.124

packages:
  - nginx
  - php5-fpm
  - git

services:
  - php5-fpm
  - nginx


nginxconfigsrc: nginx.conf.template
nginxconfigdest: /etc/nginx/sites-enabled/default

repourl: https://github.com/mzeier/pinocchio-web.git
webroot: /usr/share/nginx/html
