---
hosts:
  - 50.16.88.200
  - 54.147.243.124

packages:
  - nginx
  - php
  - git

services:
  - nginx

nginxconfig:
  - src: nginx.conf.template
  - dest: /etc/nginx/nginx.conf


repourl: https://github.com/mzeier/pinocchio-web.git
webroot: /usr/share/nginx/html
